version: '3.4'

services:
  mileston-business:
    image: mileston-business-dashboard
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
